import 'package:dio/dio.dart';
import '../core/api/dio_client.dart';
import '../models/agency/agency_model.dart';
import '../models/agency/agency_status.dart';

/// Repository for agency data management
class AgencyRepository {
  final Dio _dio = DioClient.dio;

  /// Get list of agencies with optional filters
  Future<List<Agency>> getAgencies({
    String? search,
    AgencyStatus? status,
    String? sortBy,
    bool sortAscending = true,
    int? page,
    int? limit,
  }) async {
    try {
      final queryParameters = <String, dynamic>{};

      if (search != null && search.isNotEmpty) {
        queryParameters['search'] = search;
      }
      if (status != null) {
        queryParameters['status'] = status.name;
      }
      if (sortBy != null) {
        queryParameters['sort_by'] = sortBy;
        queryParameters['sort_order'] = sortAscending ? 'asc' : 'desc';
      }
      if (page != null) {
        queryParameters['page'] = page;
      }
      if (limit != null) {
        queryParameters['limit'] = limit;
      }

      final response = await _dio.get(
        '/agencies',
        queryParameters: queryParameters,
      );

      // API returns direct array, not wrapped in {agencies: [...]}
      final agencies = response.data as List<dynamic>;

      return agencies
          .map((json) => Agency.fromJson(json as Map<String, dynamic>))
          .toList();
    } on DioException catch (e) {
      throw _handleError(e);
    } catch (e) {
      rethrow;
    }
  }

  /// Get a single agency by ID
  Future<Agency> getAgencyById(String id) async {
    try {
      final response = await _dio.get('/agencies/$id');

      return Agency.fromJson(response.data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Create a new agency
  /// ID will be generated by the backend
  Future<Agency> createAgency({
    required String name,
    required String description,
    required String category,
  }) async {
    try {
      final response = await _dio.post(
        '/agencies',
        data: {
          'name': name,
          'display_name': name, // Use name as display_name
          'description': description,
          'category': category,
        },
      );

      return Agency.fromJson(response.data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Update an existing agency
  Future<Agency> updateAgency(String id, Map<String, dynamic> updates) async {
    try {
      final response = await _dio.put('/agencies/$id', data: updates);

      return Agency.fromJson(response.data as Map<String, dynamic>);
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Delete an agency
  Future<void> deleteAgency(String id) async {
    try {
      await _dio.delete('/agencies/$id');
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Get introduction for an agency
  Future<Map<String, String>> getIntroduction(String agencyId) async {
    try {
      final response = await _dio.get('/agencies/$agencyId/specification/introduction');
      final spec = response.data['specification'] as Map<String, dynamic>?;
      final introduction = spec?['introduction'] as Map<String, dynamic>?;
      
      // Convert to Map<String, String>
      if (introduction != null) {
        return introduction.map((key, value) => MapEntry(key, value.toString()));
      }
      return {};
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Save introduction for an agency
  Future<void> saveIntroduction(
    String agencyId,
    Map<String, String> introductionData,
  ) async {
    try {
      await _dio.put('/agencies/$agencyId/specification/introduction', data: {
        'introduction': introductionData,
        'updated_by': 'user', // TODO: Get from auth context
      });
    } on DioException catch (e) {
      throw _handleError(e);
    }
  }

  /// Handle DioException and convert to appropriate error
  Exception _handleError(DioException error) {
    if (error.response != null) {
      final statusCode = error.response!.statusCode;
      
      // Extract error details from response
      final data = error.response!.data;
      String message;
      
      if (data is Map<String, dynamic>) {
        // Backend returns structured error: {error: "...", message: "...", details: "..."}
        message = data['message'] as String? ?? 
                  data['error'] as String? ?? 
                  error.response!.statusMessage ?? 
                  'Unknown error';
        
        // Include details if available for debugging
        final details = data['details'] as String?;
        if (details != null && details.isNotEmpty) {
          message = '$message\nDetails: $details';
        }
      } else {
        message = error.response!.statusMessage ?? 'Unknown error';
      }

      switch (statusCode) {
        case 400:
          return Exception('Invalid input: $message');
        case 401:
          return Exception('Authentication required: $message');
        case 403:
          return Exception('Access denied: $message');
        case 404:
          return Exception('Agency not found: $message');
        case 500:
          return Exception('Server error: $message');
        default:
          return Exception('Error ($statusCode): $message');
      }
    } else if (error.type == DioExceptionType.connectionTimeout ||
        error.type == DioExceptionType.receiveTimeout) {
      return Exception(
        'Connection timeout. Please check your internet connection.',
      );
    } else if (error.type == DioExceptionType.connectionError) {
      return Exception(
        'Connection error. Please check your internet connection.',
      );
    } else {
      return Exception('An unexpected error occurred: ${error.message}');
    }
  }
}
